// Code generated by Prismic. DO NOT EDIT.

import Content from "./Content";
import Cta from "./Cta";
import EducatorPresentation from "./EducatorPresentation";
import FaqSection from "./FaqSection";
import FeaturedCaseStudies from "./FeaturedCaseStudies";
import Hero from "./Hero";
import ImageText from "./ImageText";
import VideoEmbed from "./VideoEmbed";

export const components = {
	content: Content,
	cta: Cta,
	educator_presentation: EducatorPresentation,
	faq_section: FaqSection,
	featured_case_studies: FeaturedCaseStudies,
	hero: Hero,
	image_text: ImageText,
	video_embed: VideoEmbed
};